[package]
name = "vidro-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
lru = "0.8"
lazy_static = "1.4"

[profile.release]
opt-level = 3
lto = "fat"   # もっとも強力だがコンパイルは重い
codegen-units = 1
panic = "abort"

target-cpu = "native"
